### PR TITLE
Implement v4 NFS export and v12 SMB share API

### PR DESCRIPTION
**Pull request by P-Cao**
Use structs generated by Open API to implement nfs exports and smb share Add testing codes

# PR Submission checklist

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/888|

# Common PR Checklist:

- [x] Have you made sure that the code compiles?
- [x] Have you commented your code, particularly in hard-to-understand areas
- [ ] Did you run tests in a real Kubernetes cluster?
- [x] Have you maintained backward compatibility

# Tests:
```
time="2023-07-10T03:09:02-04:00" level=debug msg="opts.Insecure : 'true'"
time="2023-07-10T03:09:02-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/latest/ HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:03-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:05 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
**=== RUN   TestClient_ListExportsWithStructParams**
time="2023-07-10T03:09:03-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/4/protocols/nfs/exports/?limit=600 HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:03-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, POST, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:05 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:03-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/4/protocols/nfs/exports/?resume=1-1-MAAA1-MAAA6-MjA3MDg33-NjAw3-NjAw0-1-MgAA2-aWQA6-MjA3MDg332-YmUzYTI0NDdhZGE1ZDZlMmVkNjc0YjUxM2UxMmJjMzAA1-MQAA HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:04-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, POST, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:06 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
**--- PASS: TestClient_ListExportsWithStructParams (1.09s)**
**=== RUN   TestClient_ExportLifeCycleWithStructParams**
time="2023-07-10T03:09:04-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    PUT /namespace/ifs/data/tf_nfs_export_test HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    X-Isi-Ifs-Access-Control: 0777\n    X-Isi-Ifs-Target-Type: container\n    \n"
time="2023-07-10T03:09:04-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, POST, DELETE, HEAD\n    Content-Security-Policy: default-src 'none'\n    Content-Type: text/plain\n    Date: Mon, 10 Jul 2023 07:09:06 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Isi-Ifs-Spec-Version: 1.0\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:04-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    POST /platform/4/protocols/nfs/exports/ HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    Content-Type: application/json\n    \n    {\"paths\":[\"/ifs/data/tf_nfs_export_test\"]}\n"
time="2023-07-10T03:09:04-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 201 Created\n    Transfer-Encoding: chunked\n    Allow: GET, POST, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:06 GMT\n    Location: /4/protocols/nfs/exports/302182\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:04-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/4/protocols/nfs/exports/?limit=1 HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:04-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, POST, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:07 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:04-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/4/protocols/nfs/exports/302182 HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:05-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:07 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:05-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    PUT /platform/4/protocols/nfs/exports/302182 HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    Content-Type: application/json\n    \n    {\"read_only\":true}\n"
time="2023-07-10T03:09:05-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 204 No Content\n    Content-Length: 0\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Date: Mon, 10 Jul 2023 07:09:07 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:05-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/4/protocols/nfs/exports/302182 HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:05-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:07 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:05-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    DELETE /platform/4/protocols/nfs/exports/302182 HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:05-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 204 No Content\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Date: Mon, 10 Jul 2023 07:09:07 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:05-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/4/protocols/nfs/exports/302182 HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:05-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 404 Not Found\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:07 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:05-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    DELETE /namespace/ifs/data/tf_nfs_export_test?recursive=true HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:05-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 204 No Content\n    Allow: GET, PUT, POST, DELETE, HEAD\n    Content-Security-Policy: default-src 'none'\n    Date: Mon, 10 Jul 2023 07:09:08 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Isi-Ifs-Spec-Version: 1.0\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:05-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    DELETE /namespace/ifs/data/tf_nfs_export_test?recursive=true HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:05-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 204 No Content\n    Allow: GET, PUT, POST, DELETE, HEAD\n    Content-Security-Policy: default-src 'none'\n    Date: Mon, 10 Jul 2023 07:09:08 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Isi-Ifs-Spec-Version: 1.0\n    X-Xss-Protection: 1; mode=block\n    "
**--- PASS: TestClient_ExportLifeCycleWithStructParams (1.50s)**
**=== RUN   TestClient_SmbShareWithStructParams**
time="2023-07-10T03:09:05-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/12/protocols/smb/shares/?limit=1 HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:06-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, POST, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:08 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:06-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/12/protocols/smb/shares/?resume=1-1-MAAA1-MAAA1-MQAA1-MQAA1-MgAA0-1-MQAA32-ZThlYTk2Y2Q3YTkyYTc0MGQ4YTM4M2JlOGI0MTMzYTUA6-cHRyX3Rm6-cHRyX3Rm HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:06-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, POST, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:08 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:06-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/12/protocols/smb/shares/?resume=1-1-MAAA1-MAAA1-MQAA1-MgAA1-MgAA0-1-MQAA32-ZThlYTk2Y2Q3YTkyYTc0MGQ4YTM4M2JlOGI0MTMzYTUA13-c2hhcmVfaW5oZXJpdAAA13-c2hhcmVfaW5oZXJpdAAA HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:06-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, POST, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:08 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:06-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/12/protocols/smb/shares/?resume=1-1-MAAA1-MAAA1-MQAA1-MwAA1-MgAA0-1-MQAA32-ZThlYTk2Y2Q3YTkyYTc0MGQ4YTM4M2JlOGI0MTMzYTUA10-dGVzdF9zaGFyZQAA10-dGVzdF9zaGFyZQAA HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:06-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, POST, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:08 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
**--- PASS: TestClient_SmbShareWithStructParams (1.01s)**
**=== RUN   TestClient_SmbShareLifeCycleWithStructParams**
time="2023-07-10T03:09:06-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    POST /platform/12/protocols/smb/shares/ HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    Content-Type: application/json\n    \n    {\"name\":\"tf_share\",\"path\":\"/ifs/data\",\"permissions\":[{\"permission\":\"full\",\"permission_type\":\"allow\",\"trustee\":{\"id\":\"SID:S-1-1-0\",\"name\":\"Everyone\",\"type\":\"wellknown\"}}]}\n"
time="2023-07-10T03:09:06-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 201 Created\n    Transfer-Encoding: chunked\n    Allow: GET, POST, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:09 GMT\n    Location: /12/protocols/smb/shares/tf_share\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:06-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/12/protocols/smb/shares/?limit=1 HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:07-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, POST, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:09 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:07-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/12/protocols/smb/shares/tf_share HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:07-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:09 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:07-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    PUT /platform/12/protocols/smb/shares/tf_share HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    Content-Type: application/json\n    \n    {\"ca_timeout\":112}\n"
time="2023-07-10T03:09:07-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 204 No Content\n    Content-Length: 0\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Date: Mon, 10 Jul 2023 07:09:09 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:07-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/12/protocols/smb/shares/tf_share HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:07-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:10 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:07-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    DELETE /platform/12/protocols/smb/shares/tf_share HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:08-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 204 No Content\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Date: Mon, 10 Jul 2023 07:09:10 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-10T03:09:08-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/12/protocols/smb/shares/tf_share HTTP/1.1\n    Host: 10.230.24.241:8080\n    Authorization: root:******\n    \n"
time="2023-07-10T03:09:08-04:00" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 404 Not Found\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Mon, 10 Jul 2023 07:09:10 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
**--- PASS: TestClient_SmbShareLifeCycleWithStructParams (1.42s)**
PASS
ok      github.com/dell/goisilon        5.266s


```

## Description of your changes:
<your change goes here>

### CODE REVIEW

**Review by shefali-malhotra — CHANGES_REQUESTED** [review]
Please update complete UT test results.

**Comment by P-Cao** [comment]
> ate complete UT test results.

Do we have a pipeline for generating UT report?

**Comment by chimanjain** [comment]
Can you mention the steps/procedure for generating structs using Open API.

**Comment by P-Cao** [comment]
> Can you mention the steps/procedure for generating structs using Open API.

Actually, I generated openapi lib using [spec](https://developer.dell.com/apis/4088/versions/9.4.0/9.4.0.0_ISLANDER_OAS2.json). And then manually picked the structs related to smb share & nfs export into openapi folder and there should be no harm to other modules.

**Comment by P-Cao** [comment]
> Please update complete UT test results.

Done

**Review by shefali-malhotra — APPROVED** [review]
LGTM

**Review by NavisJ — APPROVED** [review]

**Review by forrestxia — APPROVED** [review]

**Pull request merged**
