### PR TITLE
Implement API for user and role

### PR DESCRIPTION
**Pull request by taohe1012**
Implement API for user and role to support PowerScale Terraform Provider:
 - add CRUD API for user
 - add Get API for role
 - add add/remove roleMemebr API for role

# PR Submission checklist

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/888 |

# Common PR Checklist:

- [x] Have you made sure that the code compiles?
- [x] Have you commented your code, particularly in hard-to-understand areas
- [ ] Did you run tests in a real Kubernetes cluster?
- [x] Have you maintained backward compatibility

All unit tests for role and user are passed:
```

time="2023-07-05T04:29:59Z" level=debug msg="opts.Insecure : 'true'"
time="2023-07-05T04:29:59Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/latest/ HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:00Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:30:55 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
=== RUN   TestRoleGet
time="2023-07-05T04:30:00Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/1/auth/roles/?resolve_names=true&limit=1000 HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:00Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, POST, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:30:55 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:00Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/1/auth/roles/ HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:00Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, POST, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:30:55 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
--- PASS: TestRoleGet (0.67s)
=== RUN   TestRoleMemberAdd
time="2023-07-05T04:30:00Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/1/auth/roles/SystemAdmin HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:00Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:30:56 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:00Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    POST /platform/1/auth/users/ HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    Content-Type: application/json\n    \n    {\"name\":\"test_user_roleMember\"}\n"
time="2023-07-05T04:30:01Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 201 Created\n    Transfer-Encoding: chunked\n    Allow: GET, POST, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:30:56 GMT\n    Location: /1/auth/users/SID%!A(MISSING)S-1-5-21-2193650305-1279797252-961391754-1129\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:01Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/1/auth/users/USER:test_user_roleMember HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:01Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:30:56 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:01Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/1/auth/roles/SystemAdmin HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:01Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:30:56 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:01Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    POST /platform/1/auth/roles/SystemAdmin/members/ HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    Content-Type: application/json\n    \n    {\"name\":\"test_user_roleMember\",\"type\":\"user\"}\n"
time="2023-07-05T04:30:01Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 201 Created\n    Transfer-Encoding: chunked\n    Allow: GET, POST, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:30:56 GMT\n    Location: /1/auth/roles/SystemAdmin/members/UID%!A(MISSING)2106\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:01Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/1/auth/roles/SystemAdmin HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:02Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:30:57 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:02Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    DELETE /platform/1/auth/roles/SystemAdmin/members/USER:test_user_roleMember HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:02Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 204 No Content\n    Allow: DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Date: Wed, 05 Jul 2023 04:30:57 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:02Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/1/auth/roles/SystemAdmin HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:03Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:30:57 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:03Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    POST /platform/1/auth/roles/SystemAdmin/members/ HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    Content-Type: application/json\n    \n    {\"id\":\"UID:2106\",\"type\":\"user\"}\n"
time="2023-07-05T04:30:03Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 201 Created\n    Transfer-Encoding: chunked\n    Allow: GET, POST, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:30:58 GMT\n    Location: /1/auth/roles/SystemAdmin/members/UID%!A(MISSING)2106\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:03Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/1/auth/roles/SystemAdmin HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:03Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:30:58 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:03Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    DELETE /platform/1/auth/roles/SystemAdmin/members/UID:2106 HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:03Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 204 No Content\n    Allow: DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Date: Wed, 05 Jul 2023 04:30:58 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:03Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/1/auth/roles/SystemAdmin HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:04Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:30:59 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:04Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    DELETE /platform/1/auth/users/USER:test_user_roleMember HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:04Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 204 No Content\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Date: Wed, 05 Jul 2023 04:30:59 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
--- PASS: TestRoleMemberAdd (3.72s)
=== RUN   TestUserGet
time="2023-07-05T04:30:04Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/1/auth/users/?cached=false&filter=admin&resolve_names=false&query_member_of=false&limit=1000 HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:04Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, POST, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:30:59 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:04Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/1/auth/users/ HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:04Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, POST, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:30:59 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
--- PASS: TestUserGet (0.39s)
=== RUN   TestUserCreate
time="2023-07-05T04:30:04Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    POST /platform/1/auth/users/ HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    Content-Type: application/json\n    \n    {\"email\":\"test.dell.com\",\"name\":\"test_user_create_options\",\"password\":\"****\",\"uid\":100000}\n"
time="2023-07-05T04:30:05Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 201 Created\n    Transfer-Encoding: chunked\n    Allow: GET, POST, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:31:00 GMT\n    Location: /1/auth/users/SID%!A(MISSING)S-1-5-21-2193650305-1279797252-961391754-1130\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:05Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/1/auth/users/UID:100000 HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:05Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:31:00 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:05Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    DELETE /platform/1/auth/users/UID:100000 HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:05Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 204 No Content\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Date: Wed, 05 Jul 2023 04:31:00 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:05Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/1/auth/users/UID:100000 HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:05Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 404 Not Found\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:31:00 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
--- PASS: TestUserCreate (0.89s)
=== RUN   TestUserUpdate
time="2023-07-05T04:30:05Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    POST /platform/1/auth/users/ HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    Content-Type: application/json\n    \n    {\"name\":\"test_user_create_update\"}\n"
time="2023-07-05T04:30:05Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 201 Created\n    Transfer-Encoding: chunked\n    Allow: GET, POST, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:31:01 GMT\n    Location: /1/auth/users/SID%!A(MISSING)S-1-5-21-2193650305-1279797252-961391754-1131\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:05Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/1/auth/users/USER:test_user_create_update HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:06Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:31:01 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:06Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    PUT /platform/1/auth/users/USER:test_user_create_update?force=true HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    Content-Type: application/json\n    \n    {\"email\":\"test.dell.com\",\"password\":\"****\",\"uid\":100000}\n"
time="2023-07-05T04:30:06Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 204 No Content\n    Content-Length: 0\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Date: Wed, 05 Jul 2023 04:31:01 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:06Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/1/auth/users/USER:test_user_create_update HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:06Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n    Transfer-Encoding: chunked\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Content-Type: application/json\n    Date: Wed, 05 Jul 2023 04:31:01 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
time="2023-07-05T04:30:06Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    DELETE /platform/1/auth/users/USER:test_user_create_update HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:06Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 204 No Content\n    Allow: GET, PUT, DELETE, HEAD\n    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';\n    Date: Wed, 05 Jul 2023 04:31:01 GMT\n    Server: Apache\n    Strict-Transport-Security: max-age=31536000;\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: sameorigin\n    X-Xss-Protection: 1; mode=block\n    "
--- PASS: TestUserUpdate (1.20s)
PASS
ok  	github.com/dell/goisilon	7.129s

```

### CODE REVIEW

**Review by P-Cao — APPROVED** [review]

**Review by NavisJ — APPROVED** [review]

**Review by shefali-malhotra — CHANGES_REQUESTED** [review]
Please update complete UT test results.

**Comment by taohe1012** [comment]
> Please update complete UT test results.

hi @shefali-malhotra , update the total test results of user and role

**Review by chimanjain — APPROVED** [review]

**Comment by chimanjain** [comment]
LGTM

**Comment by taohe1012** [comment]
hi @shefali-malhotra , the total test results were updated, can you help take a look

**Review by shefali-malhotra — APPROVED** [review]
LGTM

**Pull request merged**
